apps/accounts/urls.py
from apps.accounts.views import LoginView, LogoutView, SignupView
from django.urls import path

app_name = 'accounts'
urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

apps/polls/urls.py
from apps.polls.views.detail import DetailView
from apps.polls.views.index import IndexView
from apps.polls.views.results import ResultsView
from django.urls import path

app_name = 'polls'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<int:pk>/', DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', ResultsView.vote, name='vote'),
]

core/urls.py
from django.contrib import admin
#from django.shortcuts import redirect
from django.urls import include, path

from core.views import HomeView

urlpatterns = [
    # for more redirect's usage options: https://docs.djangoproject.com/en/4.1/topics/http/shortcuts/
    #path('', lambda request: redirect('polls/', permanent=False)),
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('apps.accounts.urls')),
    path('polls/', include('apps.polls.urls')),
]

templates/home.html
{% extends 'mainsecure.html' %}

{% block content %}

    <div class="jumbotron">
        <h1 class="display-4">Olá mundo!</h1>
        <p class="lead">Este é um exemplo simples de uma aplicação usando Bootstrap 5.2 e Django 4.1, com autentição.</p>
        <hr class="my-4">
        <p>Registre-se agora para ter acesso total ao aplicativo</p>
        <p class="lead">
            <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Registrar</a>
        </p>
    </div>

{% endblock content %}

templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Milton C. S. Junior, NewTi Soluções">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'fontawesome/fa/bootstrap.icons.min.css' %}">

    <!-- Title -->
    <title>{% block title %}Exemplo Django + Bootstrap{% endblock title %}</title>

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="{% static 'img/bootstrap-logo.png' %} sizes=" 180x180">
    <link rel="icon" href="{% static 'img/bootstrap-logo.png' %}">
    <meta name="theme-color" content="#343a40">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img id="logo" src="{% static 'img/bootstrap-logo.png' %}" alt="Logo" width="40" height="40">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href={% url 'home' %}>Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'polls:index' %}">Polls</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Ações
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Ação 1</a></li>
                            <li><a class="dropdown-item" href="#">Ação 2</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Ação diferenciada</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled">Desativado</a>
                    </li>
                </ul>
                {% block authentication %}
                {% endblock authentication %}
            </div>
        </div>
    </nav>


    <main class="container">
        {% block content %}
        {% endblock content %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/app.validations.js' %}"></script>
</body>

</html>

templates/mainsecure.html
{% extends 'main.html' %}

{% block title %} {{ block.super }} v. 0.0.1{% endblock title %}

{% block authentication %}

    {% if user.is_authenticated %}
        <ul class="navbar-nav d-flex">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {{ user.get_full_name }} 
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Ação 1</a></li>
                    <li><a class="dropdown-item" href="#">Ação 2</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href={% url 'accounts:logout' %}>Sair</a></li>
                </ul>
            </li>
        </ul>
    {% else %}
        <form action={% url 'accounts:login' %} method="get" class="d-flex">
            {% csrf_token %}
            <button class="btn btn-outline-light" type="submit">Entrar</button>
        </form>
    {% endif %}

{% endblock authentication %}

{% block content %}
    {{ block.super }}
{% endblock content %}